### ISSUE TITLE
New 'status' command

### ISSUE THREAD

**Issue by rosieyohannan** [ReconfigureIO/reco#46]
`$ reco build status foobar`
`status: errored`

(the different options need fleshing out here)

**Comment by pwaller** [comment]
What is the use case for this command?

Also, `foobar` is a build ID, is it? If so, please edit the body to `reco build status <build id>`.

**Comment by CampGareth** [comment]
Hmm, well normally you'd see the status using `reco build list` but I could see that list becoming too long to pluck out the status of the build you want to examine. There may be other solutions to this though like making the list ordered from build with newest-most-recent event to oldest-most-recent event. I'm not a fan of adding commands that require users to remember UUIDs, we should be transitioning away from UUIDs as user-facing identifiers in my opinion.

**Comment by pwaller** [comment]
Does `reco build logs` or `reco build list` not currently solve the problem, in a sense?

I'm not sure adding another command is the right way to go, if it can be avoided. My concern is that the more commands we have, the harder it is for users to discover things. It would be good to understand the rationale for adding it. If the complaint is that `reco build list` gets too long, maybe that is the problem to solve.

**Comment by rosieyohannan** [comment]
Yeah I think we can just drop this, I shouldn't have really put it here, was just clearing Trello and didn't think it through properly. On-prem can use reco build list, Cloud users can either use that or look at their Dashboard. (Hopefully on-prem people will have Dashboard too at some stage)
